# Generated by Django 4.2.5 on 2023-09-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_alter_reserva_quitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='quitado',
            field=models.BooleanField(),
        ),
    ]
